name: 'Check Download Status'
description: 'Checks download status of marked downloads'
author: 'd10sfan'
runs:
    using: 'node20'
    main: 'dist/index.js'
outputs:
  matrix:
    description: Matrix
